name: C-Linter
description: |
  C/C++: clang-tidy, clang-format, and cppcheck.
  Automatically checks pull requests changes and posts the comment with result.
author: Israel Roldan [airvzxf]
branding:
  icon: activity
  color: green
inputs:
  project_path:
    description: 'Project Directory.'
    required: false
    default: '.'
  cppcheck_options:
    description: 'Additional cppcheck options.'
    required: false
    default: '--enable=warning'
runs:
  using: 'docker'
  image: 'Dockerfile'
