name: C-Linter
description: |
  C/C++: clang-tidy, clang-format, and cppcheck.
  Automatically checks pull requests changes and posts the comment with result.
author: Israel Roldan [airvzxf]
branding:
  icon: activity
  color: green
inputs:
  scan_full_project:
    description: 'Scan full project, not only the committed files.'
    required: false
    default: 'false'
  project_path:
    description: 'Project Directory.'
    required: false
    default: '.'
  build_type:
    description: 'Build type.'
    required: false
    default: 'Release'
  c_extensions:
    description: 'File extensions for C/C++.'
    required: false
    default: >
      \.c$|\.cc$|\.cp$|\.cpp$|\.cu$|\.cuh$|\.cx$|\.cxx$|\.h$|\.hh$|\.hp$|\.hpp$|\.hx$|\.hxx$
  clang_tidy_options:
    description: 'Additional options of CLang Tidy.'
    required: false
    default: >-
      --format-style=llvm
      --warnings-as-errors=*
      --header-filter=.*
      --checks=*
  clang_format_options:
    description: 'Additional options of CLang Format.'
    required: false
    default: >-
      --style=LLVM
      --sort-includes
      --Werror
      --dry-run
  cppcheck_options:
    description: 'Additional options of CPP Check.'
    required: false
    default: >-
      --language=c
      --std=c11
      --platform=unix64
      --suppress=missingIncludeSystem
      --enable=all
      --inconclusive
      --force
      --max-ctu-depth=1000000
      --library=boost.cfg
      --library=cppcheck-lib.cfg
      --library=cppunit.cfg
      --library=gnu.cfg
      --library=libcerror.cfg
      --library=posix.cfg
      --library=std.cfg
      --template="----------\n{file}\nMessage: {message}\n  Check: CWE-{cwe} [{severity} -> {id}]\n  Stack: {callstack}\n   Line: {line}:{column}\n{code}\n"
      --template-location="----------\n{file}\nNote: {info}\nLine: {line}:{column}\n{code}\n"
      --project=build/compile_commands.json
  install_packages:
    description: 'Install extra package to compile your code inside of this action.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
