name: C-Linter
description: |
  C/C++: clang-tidy, clang-format, and cppcheck.
  Automatically checks pull requests changes and posts the comment with result.
author: Israel Roldan [airvzxf]
branding:
  icon: activity
  color: green
inputs:
  project_path:
    description: 'Project Directory.'
    required: false
    default: '.'
  build_type:
    description: 'Build type.'
    required: false
    default: 'Release'
  c_extensions:
    description: 'File extensions for C/C++.'
    required: false
    default: ''
  clang_tidy_options:
    description: 'Additional options of CLang Tidy.'
    required: false
    default: ''
  clang_format_options:
    description: 'Additional options of CLang Format.'
    required: false
    default: ''
  cppcheck_options:
    description: 'Additional options of CPP Check.'
    required: false
    default: '--enable=warning'
  install_packages:
    description: 'Install extra package to compile your code inside of this action.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
